### ISSUE TITLE
Install does not install requirements

### ISSUE THREAD

**Issue by johnrork** [jakeanderson1/hey_helper#3]
```johnr in ~/hey_helper [master ≡]
→ pip install .
Processing /Users/johnr/hey_helper
Installing collected packages: hey-helper
  Running setup.py install for hey-helper ... done
Successfully installed hey-helper-0.0.1
You are using pip version 9.0.1, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
johnr in ~/hey_helper [master ≡]
→ hey
Traceback (most recent call last):
  File "/usr/local/bin/hey", line 11, in <module>
    load_entry_point('hey-helper==0.0.1', 'console_scripts', 'hey')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/hey_helpers/hey_helpers.py", line 6, in <module>
    from yaml import load
ModuleNotFoundError: No module named 'yaml'
```

**Comment by johnrork** [comment]
Fixed.
